# Generated by Django 4.1.3 on 2023-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_favorite',
            field=models.BooleanField(db_column='is_favorite', default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_favorite',
            field=models.BooleanField(db_column='is_favorite', default=False),
        ),
    ]
